version: '3'
services:
  server:
    image: gocd/gocd-server:v18.9.0
    ports:
      - 8153:8153
      - 8154:8154
    volumes:
      - ./server-data:/godata
  agent:
    image: gocd/gocd-agent-alpine-3.8:v18.9.0
    depends_on:
      - server
    environment:
      GO_SERVER_URL: https://server:8154/go
    volumes:
    - ./agent-data:/godata